### ISSUE TITLE
Configuration persistence

### ISSUE THREAD

**Issue by fniko** [cn-terraform/terraform-aws-networking#2]
Hi,
I did not find any information about backing up the Nexus configuration.
Is it missing or how should I achieve it?

**Comment by jnonino** [comment]
The purpose of this module is to create a network platform for other modules. It creates a VPC, public and private subnets, internet and NAT gateways, etc

**Comment by fniko** [comment]
Hi, it seems like a missed the right github :D Sorry and closing! :)
